### PR TITLE
Add step to Splunk app setup instructions for Windows

### PR DESCRIPTION
**Pull request by paulkva**
When testing this Splunk app on Windows, I was getting a somewhat cryptic error in splunkd.log. Upon further investigation I discovered the instructions in the defaults/inputs.conf file. This PR should make those instructions more discoverable.

### CODE REVIEW

**Comment by wfg** [comment]
Hey sorry, @paulkva, this PR was mixed in with Dependabot stuff, so I overlooked it.

It sounds like the issue stems from `local\inputs.conf` created during app installation. Since the Linux configuration is the default, it gets copied into `local\` (instead of the Windows configuration). This means that the instructions in `inputs.conf` should be performed in `local\` instead of `default\`. Does this sound correct to you?

**Comment by paulkva** [comment]
No worries on the delay. Yes, the change to `inputs.conf` is more important in `local\` than it is in `default\`. Since it has been a while, I can't remember offhand if I had to make the changes in `default\` in order for the installation to succeed. If the changes in `default\inputs.conf` don't matter, then it would be good to _also_ update the instructions at the top of that file accordingly.

**Comment by mwilco03** [comment]
With some pythonic tricks could determine OS and programmatically generate OS specific files. 
If this is something that would be desired feel free to chime in.

**Comment by paulkva** [comment]
That would certainly improve the user experience, yes! I of course can't comment on where that would fall compared to any other priorities.

**Comment by wfg** [comment]
Made a README change in the new repo. Closing. Thanks @paulkva!

**Pull request closed without merging**
