### PR TITLE
Update poll_incidents.py

### PR DESCRIPTION
**Pull request by mwilco03**
Reverses offset functionality, in lue of range which counts down and was consistently storing value ≈50. 
With this method we take the total passing it into for loop and iterating over the modulus of 50 if equal to 0 appending it to an array.
Reversing the list we start off with the highest moving to the lowest ends with the highest serial number.

### CODE REVIEW

**Comment by mwilco03** [comment]
As I have seen this play out, and it may be my specific instance. 

The offset 0 returns the highest serial number. (last in first out)

If the highest serial number is 200.
total_count = 200
for i in range(0, total_count, 50):
     print(i)
offset 0 returns {SerialNum:200} as the Highest Serial Number Observed
offset 50 returns {SerialNum:150} as the Highest Serial Number Observed
offset 100 returns {SerialNum:100} as the Highest Serial Number Observed
offset 150 returns {SerialNum:50} as the Highest Serial Number Observed
finally 50 is the Higest SerialNum Observed write to file.

This causes the highest seen serial number to be something close to 50 every time.
My code has forked pretty dramatically so it wouldn't be surprising if it were just mine. 
@wfg if you could check with customers to see what is being stored in the last indexed value.
If I'm correct reversing it resolves the issue in the least intrusive manor.

total_count = 200
offset_list = []
for i in range(0, total_count, 50):
     offset_list.append(i)
     offset_list.reverse()

offset 150 returns {SerialNum:50} as the Highest Serial Number Observed
offset 100 returns {SerialNum:100} as the Highest Serial Number Observed
offset 50 returns {SerialNum:150} as the Highest Serial Number Observed
offset 0 returns {SerialNum:200} as the Highest Serial Number Observed
finally 200 is the Higest SerialNum Observed serial number written to file.

**Comment by wfg** [comment]
Wow. This is a good catch.

However, the direction of the offset should not affect the highest serial number indexed. The "highest" should be the highest. A quick look shows that `highest_serialNum` is actually [reset to `0`](https://github.com/twistlock/sample-code/blob/master/siem/splunk/twistlock/bin/poll_incidents.py#L83) every API call.

**Comment by wfg** [comment]
New version published to GitHub. This is the relevant commit: https://github.com/twistlock/sample-code/commit/c70f510edbe0f344b4a3721586ed35c41a0cb48c

**Comment by mwilco03** [comment]
@wfg sounds good closing request

**Pull request closed without merging**
